---
- hosts: localhost
  become: true
  become_user: root

  tasks:
  - name: Start docker
    service: name=docker state=started

  - name: create docker image using war file
    command: docker build -t myproject2:CICD .
    args:
      #chdir: /opt/myproject2
      chdir: /var/lib/jenkins/jenkins_slave/workspace/Final_Project_Myproject2

  - name: create tag to image
    command: docker tag myproject2:CICD raj101/myproject2:CICD

  - name: loginto docker
    command: docker login --username raj101 --password JunkPassw0rd@9876

  - name: push image on to dockerhub
    command: docker push raj101/myproject2:CICD
    
  - name: Do deployment in Docker Swarm cluster
    command: docker service create --name mysvc-ansible --replicas 1 -p 8282:8085 raj101/myproject2:CICD
    
  - name: remove docker images form ansible server
    command: docker rmi myproject2:CICD raj101/myproject2:CICD
    ignore_errors: yes
    
  - name: Do deployment to kuberetes Prod
    # command: kubectl apply -f https://raw.githubusercontent.com/devops-learner01012022/DevOps_ClassNotes/master/CICD%20pipeline/kubedeployment.yml
    # command: kubectl apply -f /opt/myproject2/kubedeployment.yml
    command: kubectl apply -f https://github.com/rrgit101/rrcicd-pipeline-train-schedule-autodeploy/blob/main/train-schedule-kube.yml
